SHELL := /bin/bash

.PHONY: help install build test run

help:
	@echo "application targets: install, build, test, run"

install:
	@echo "TODO: bun install"

build:
	@echo "TODO: bun build"

test:
	@echo "TODO: bun test"

run:
	@echo "TODO: start application services"
