SHELL := /bin/bash

.PHONY: help up down recycle

help:
	@echo "infra targets: up, down, recycle"

up:
	@echo "TODO: bring up k3d cluster"

down:
	@echo "TODO: tear down k3d cluster"

recycle: down up
