help:
	@echo "Available commands:"
	@echo "  clean   - Clean the project"
	@echo "  build   - Build the project"
	@echo "  cycle   - down, clean, build, up"
	@echo "  up 	 - Deploy the project in dev"
	@echo "  down 	 - Undeploy the project in dev"

