SHELL := /bin/bash

.PHONY: help build deploy test

help:
	@echo "platform targets: build, deploy, test"

build:
	@echo "TODO: package platform manifests"

deploy:
	@echo "TODO: apply kustomize stack"

test:
	@echo "TODO: run platform smoke tests"
