SHELL := /bin/bash

.PHONY: help install dev build lint test

help:
	@echo "ui targets: install, dev, build, lint, test"

install:
	@echo "TODO: bun install"

dev:
	@echo "TODO: bun run dev"

build:
	@echo "TODO: bun run build"

lint:
	@echo "TODO: bun run lint"

test:
	@echo "TODO: bun run test"
